topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
- name    : final_ajustment
  topic   : cmd_vel_ajustment
  timeout : 0.5
  priority: 3
- name    : move_base
  topic   : cmd_vel_move_base
  timeout : 3.0
  priority: 2
- name    : nav2d
  topic   : cmd_vel_nav2d
  timeout : 0.5
  priority: 1  
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
